# Generated by Django 2.2.5 on 2019-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='social_image/default.jpg', null=True, upload_to=''),
        ),
    ]
