# Generated by Django 2.2.5 on 2019-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_image',
            field=models.ImageField(null=True, upload_to='social_image'),
        ),
    ]
