# Generated by Django 2.2.5 on 2019-09-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default/default.jpg', null=True, upload_to=''),
        ),
    ]
