# Generated by Django 2.2.5 on 2019-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190916_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
