extra_data = {
    "login": "siscopuig",
    "id": 4728135,
    "node_id": "MDQ6VXNlcjQ3MjgxMzU=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/4728135?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/siscopuig",
    "html_url": "https://github.com/siscopuig",
    "followers_url": "https://api.github.com/users/siscopuig/followers",
    "following_url": "https://api.github.com/users/siscopuig/following{/other_user}",
    "gists_url": "https://api.github.com/users/siscopuig/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/siscopuig/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/siscopuig/subscriptions",
    "organizations_url": "https://api.github.com/users/siscopuig/orgs",
    "repos_url": "https://api.github.com/users/siscopuig/repos",
    "events_url": "https://api.github.com/users/siscopuig/events{/privacy}",
    "received_events_url": "https://api.github.com/users/siscopuig/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Sisco Puig",
    "company": null,
    "blog": "https://siscopuig.com",
    "location": "Berlin",
    "email": "sisco@siscopuig.com",
    "hireable": null,
    "bio": null,
    "public_repos": 11,
    "public_gists": 1,
    "followers": 2,
    "following": 2,
    "created_at": "2013-06-18T12:14:18Z",
    "updated_at": "2019-08-20T17:36:33Z"
}